---
# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
apiVersion: {{ include "daemonsetversion" . }}
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
    gardener.cloud/role: system-component
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        k8s-app: calico-node
        gardener.cloud/role: system-component
      annotations:
        {{- if semverCompare "< 1.16" .Capabilities.KubeVersion.GitVersion }}
        # This, along with the CriticalAddonsOnly toleration below,
        # marks the pod as a critical add-on, ensuring it gets
        # priority scheduling and that its resources are reserved
        # if it ever gets evicted.
        scheduler.alpha.kubernetes.io/critical-pod: ''
        {{- end }}
        checksum/configmap-calico: {{ include (print $.Template.BasePath "/node/configmap-calico-config.yaml") . | sha256sum }}
    spec:
      priorityClassName: system-node-critical
      nodeSelector:
        {{- if semverCompare "<= 1.14-0" .Capabilities.KubeVersion.GitVersion }}
        beta.kubernetes.io/os: linux
        {{- else }}
        kubernetes.io/os: linux
        {{- end  }}
      hostNetwork: true
      tolerations:
        # Make sure calico-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: calico-node
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      initContainers:
      # This container installs the Calico CNI binaries
      # and CNI network config file on each node.
      - name: install-cni
        image: {{ index .Values.images "calico-cni" }}
        {{- if semverCompare "< 1.16" .Capabilities.KubeVersion.GitVersion }}
        command: ["/install-cni.sh"]
        {{- else}}
        command: ["/opt/cni/bin/install"]
        {{- end }}
        env:
          # Name of the CNI config file to create.
          - name: CNI_CONF_NAME
            value: "10-calico.conflist"
          # The CNI network config to install on each node.
          - name: CNI_NETWORK_CONFIG
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: cni_network_config
          # Set the hostname based on the k8s node name.
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          # CNI MTU Config variable
          - name: CNI_MTU
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: veth_mtu
          # Prevents the container from sleeping forever.
          - name: SLEEP
            value: "false"
        volumeMounts:
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
          - mountPath: /host/etc/cni/net.d
            name: cni-net-dir
        securityContext:
          privileged: true
        # Adds a Flex Volume Driver that creates a per-pod Unix Domain Socket to allow Dikastes
        # to communicate with Felix over the Policy Sync API.
      - name: flexvol-driver
        image: {{ index .Values.images "calico-podtodaemon-flex" }}
        volumeMounts:
          - name: flexvol-driver-host
            mountPath: /host/driver
        securityContext:
          privileged: true
      # Container just prints the content of the host /opt/cni/bin directory to check for copy failures
      - name: install-cni-check
        image: {{ index .Values.images "calico-podtodaemon-flex" }}
        command:
          - ls
          - -la
          - /host/opt/cni/bin
        volumeMounts:
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
      containers:
        # Runs calico-node container on each Kubernetes node. This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: {{ index .Values.images "calico-node" }}
          {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion  }}
          envFrom:
          - configMapRef:
              # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
              name: kubernetes-services-endpoint
              optional: true
          {{- end }}
          ports:
            {{- if .Values.config.monitoring.enabled }}
          - containerPort: {{  .Values.config.monitoring.felixMetricsPort }}
            name: metrics
            protocol: TCP
            {{- end}}
          env:
            {{- if eq .Values.config.ipam.type "host-local"}}
            - name: USE_POD_CIDR
              value: "true"
            {{- end }}
            {{- if .Values.config.monitoring.enabled }}
            - name: FELIX_PROMETHEUSMETRICSENABLED
              value: "{{ .Values.config.monitoring.enabled }}"
            - name: FELIX_PROMETHEUSMETRICSPORT
              value: "{{ .Values.config.monitoring.felixMetricsPort }}"
            {{- end }}
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Typha support: controlled by the ConfigMap.
            - name: FELIX_TYPHAK8SSERVICENAME
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: typha_service_name
            # Enable felix info logging.
            - name: FELIX_LOGSEVERITYSCREEN
              value: "error"
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Auto-detect the BGP IP address.
            {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion  }}
            {{- if .Values.config.ipv4.autoDetectionMethod }}
            # On metal the ip is bound to the lo interface (routing to the host).
            - name: IP_AUTODETECTION_METHOD
              value: "{{ .Values.config.ipv4.autoDetectionMethod }}"
            {{- end }}
            {{- end }}
            - name: IP
              value: "autodetect"
            # Disable IPV6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion  }}
            # Enable or Disable VXLAN on the default IP pool.
            - name: CALICO_IPV4POOL_VXLAN
              value: "Never"
            {{- end }}
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion  }}
            # Set MTU for the VXLAN tunnel device.
            - name: FELIX_VXLANMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the Wireguard tunnel device.
            - name: FELIX_WIREGUARDMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            {{- end }}
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "{{ .Values.global.podCIDR }}"
            - name: FELIX_IPINIPENABLED
              value: "{{ .Values.config.felix.ipinip.enabled }}"
            - name: "CALICO_IPV4POOL_{{ .Values.config.ipv4.pool | upper }}"
              value: "{{ .Values.config.ipv4.mode }}"
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FELIX_HEALTHENABLED
              value: "true"
            # Limit NAT port range: https://github.com/projectcalico/felix/pull/1838
            - name: FELIX_NATPORTRANGE
              value: "32768:65535"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
            limits:
              cpu: 4000m
              memory: 700Mi
          livenessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-live
              {{- if eq .Values.config.backend "bird" }}
              - -bird-live
              {{- end }}
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-ready
              {{- if eq .Values.config.backend "bird" }}
              - -bird-ready
              {{- end }}
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
              readOnly: false
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /var/lib/calico
              name: var-lib-calico
              readOnly: false
            - name: policysync
              mountPath: /var/run/nodeagent
            {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion  }}
            # For eBPF mode, we need to be able to mount the BPF filesystem at /sys/fs/bpf so we mount in the
            # parent directory.
            - name: sysfs
              mountPath: /sys/fs/
              # Bidirectional means that, if we mount the BPF filesystem at /sys/fs/bpf it will propagate to the host.
              # If the host is known to mount that filesystem already then Bidirectional can be omitted.
              mountPropagation: Bidirectional
            - name: cni-log-dir
              mountPath: /var/log/calico/cni
              readOnly: true
              {{- end }}
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-lib-calico
          hostPath:
            path: /var/lib/calico
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion  }}
        - name: sysfs
          hostPath:
            path: /sys/fs/
            type: DirectoryOrCreate
        {{- end }}
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Used to access CNI logs.
        - name: cni-log-dir
          hostPath:
            path: /var/log/calico/cni
        # Used to create per-pod Unix Domain Sockets
        - name: policysync
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/nodeagent
        # Used to install Flex Volume Driver
        # NOTE: the default path is changed to /var/lib/kubelet/volumeplugins since CoreOS does not allow write access on the default dir /usr/libexec
        - name: flexvol-driver-host
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/kubelet/volumeplugins/nodeagent~uds

